import dynamic from "next/dynamic";
import { Raleway, Work_Sans, Roboto_Mono } from "next/font/google";

import "./globals.css";

import Header from "@/components/header/Header";
import { useRouter } from "next/router";

const ThemeProvider = dynamic(() => import("@/contexts/ThemeContext"), {
  ssr: false,
});
const inter = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Sanjeewa.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="container px-2">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
